/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#dfe8ff",
        "outline-variant": "#c1c7cf",
        "surface": "#f9f9ff",
        "on-background": "#0f1c2f",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#4a6d4b",
        "on-secondary": "#ffffff",
        "tertiary": "#344556",
        "tertiary-container": "#4b5d6f",
        "surface-container-highest": "#d7e3fe",
        "primary": "#064771",
        "primary-fixed": "#cee5ff",
        "on-surface": "#0f1c2f",
        "outline": "#72787f",
        "error": "#ba1a1a",
        "secondary": "#446646",
        "on-primary-container": "#b3d8ff",
        "secondary-container": "#c5edc3",
        "background": "#f9f9ff",
        "on-surface-variant": "#42474e",
        "on-primary": "#ffffff",
        "primary-container": "#2b5f8a",
        "surface-container": "#e7eeff",
        "surface-dim": "#cedaf5",
        "primary-fixed-dim": "#9bcbfc",
        "on-tertiary-container": "#c3d6ea",
        "on-secondary-fixed-variant": "#2d4e2f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
};